export interface PaymentIvr {

    
    cardsAmex: string,
    cardsDiscover: string,
    cardsVisaMasterCard: string,
    clientNumber: string,
    contractId: number,
    createDateTime: string,
    createUserId: number,
    creditClCheckDigit: string,
    creditClCompressFlag: string,
    creditClNoticeFlag: string,
    creditClNumber: string,
    creditClPhoneFee: number,
    creditClPhoneSurcharge: number,
    creditClWebFee: number,
    creditClWebSurcharge: number,
    inquiryCollate: string,
    inquiryFee: string,
    inquiryFleet: string,
    inquiryIPP: string,
    inquiryLicense: string,
    inquiryNotice: string,
    inquiryPlate: string,
    inquiryRedlight: string,
    inquiryTicket: string,
    ivrID: number,
    paymentAll: string,
    paymentAny: string,
    paymentItem: string,
    paymentList: string,
    paymentListAny: string,
    paymentListSpecial: string,
    paymentRestore: string,
    updateDateTime: string,
    updateUserId: number
}
