import { Address } from 'cluster';
import { Observable, of } from 'rxjs';
// import { AddressSourceModel } from 'src/app/Models/Address Source/address-source-model';

const contractList: any[] = [
    {
        "name": "Suffolk",
        "identifierName": "default",
        "codeName": null,
        "payByWebCode": 0,
        "programManagerId": 3,
        "stateProvinceName": "Hawaii",
        "timeZone": null,
        "cbiDashboardLink": null,
        "passwordExpirationLength": 90,
        "mavroCode": null,
        "twoFactorEnabled": true,
        "partialPaymentValidation": true,
        "contractTypeName": null,
        "contractName": "Default",
        "programManagerName": "Jack Mack",
        "clientsID": 2,
        "contractsID": 1,
        "stateProvincesID": 1,
        "timeZonesID": 1,
        "contractTypeId": 2,
        "partialPaymentDueValidation": true,
        "active": true,
        "createUserID": 0,
        "updateUserID": 0,
        "createDatetime": "0001-01-01T00:00:00",
        "updateDatetime": "0001-01-01T00:00:00",
        "isDeleted": "N"
    }
]

const clientPaymentMode: any[] = [
    {
        "paymentModeMasterId": 160,
        "createUserId": 1,
        "updateUserId": 1,
        "createDateTime": "2022-06-23T10:41:25.977",
        "updateDateTime": "2022-06-23T10:41:25.977",
        "paymentModeDesc": "CASH",
        "paymentModeCD": "CA",
        "active": 1,
        "isDeleted": "N",
        "posCode": 1
    },
    {
        "paymentModeMasterId": 161,
        "createUserId": 1,
        "updateUserId": 1,
        "createDateTime": "2022-06-23T10:41:36.68",
        "updateDateTime": "2022-06-23T10:41:36.68",
        "paymentModeDesc": "CASH - BOND",
        "paymentModeCD": "CB",
        "active": 1,
        "isDeleted": "N",
        "posCode": 2
    },
    {
        "paymentModeMasterId": 162,
        "createUserId": 1,
        "updateUserId": 1,
        "createDateTime": "2022-06-23T10:41:45.93",
        "updateDateTime": "2022-06-23T10:41:45.93",
        "paymentModeDesc": "CREDIT CARD",
        "paymentModeCD": "CC",
        "active": 1,
        "isDeleted": "N",
        "posCode": 3
    },
    {
        "paymentModeMasterId": 163,
        "createUserId": 1,
        "updateUserId": 1,
        "createDateTime": "2022-06-23T10:41:53.817",
        "updateDateTime": "2022-06-23T10:41:53.817",
        "paymentModeDesc": "CASHIER'S CHECK",
        "paymentModeCD": "CH",
        "active": 1,
        "isDeleted": "N",
        "posCode": 4
    },
    {
        "paymentModeMasterId": 164,
        "createUserId": 1,
        "updateUserId": 1,
        "createDateTime": "2022-06-23T10:42:00.803",
        "updateDateTime": "2022-06-23T10:42:00.803",
        "paymentModeDesc": "CHECK",
        "paymentModeCD": "CK",
        "active": 1,
        "isDeleted": "N",
        "posCode": 5
    },
    {
        "paymentModeMasterId": 165,
        "createUserId": 1,
        "updateUserId": 1,
        "createDateTime": "2022-06-23T10:42:07.423",
        "updateDateTime": "2022-06-23T10:42:07.423",
        "paymentModeDesc": "CHEQUES",
        "paymentModeCD": "CQ",
        "active": 1,
        "isDeleted": "N",
        "posCode": 6
    },
    {
        "paymentModeMasterId": 166,
        "createUserId": 1,
        "updateUserId": 1,
        "createDateTime": "2022-06-23T10:42:14.853",
        "updateDateTime": "2022-06-23T10:42:14.853",
        "paymentModeDesc": "DEBIT CARD",
        "paymentModeCD": "DC",
        "active": 1,
        "isDeleted": "N",
        "posCode": 7
    },
    {
        "paymentModeMasterId": 167,
        "createUserId": 1,
        "updateUserId": 1,
        "createDateTime": "2022-06-23T10:42:35.147",
        "updateDateTime": "2022-06-23T10:42:35.147",
        "paymentModeDesc": "CHECK - BOND",
        "paymentModeCD": "KB",
        "active": 1,
        "isDeleted": "N",
        "posCode": 6
    },
    {
        "paymentModeMasterId": 168,
        "createUserId": 1,
        "updateUserId": 1,
        "createDateTime": "2022-06-23T10:42:52.463",
        "updateDateTime": "2022-06-23T10:42:52.463",
        "paymentModeDesc": "MON ORD - BOND",
        "paymentModeCD": "MB",
        "active": 1,
        "isDeleted": "N",
        "posCode": 8
    },
    {
        "paymentModeMasterId": 169,
        "createUserId": 1,
        "updateUserId": 1,
        "createDateTime": "2022-06-23T10:42:45.883",
        "updateDateTime": "2022-06-23T10:42:45.883",
        "paymentModeDesc": "MONEY ORDER",
        "paymentModeCD": "MO",
        "active": 1,
        "isDeleted": "N",
        "posCode": 8
    },
    {
        "paymentModeMasterId": 170,
        "createUserId": 1,
        "updateUserId": 1,
        "createDateTime": "2022-06-23T10:43:01.26",
        "updateDateTime": "2022-06-23T10:43:01.26",
        "paymentModeDesc": "NON CASH ENTRY",
        "paymentModeCD": "NC",
        "active": 1,
        "isDeleted": "N",
        "posCode": 0
    },
    {
        "paymentModeMasterId": 171,
        "createUserId": 1,
        "updateUserId": 1,
        "createDateTime": "2022-06-23T10:43:14.727",
        "updateDateTime": "2022-06-23T10:43:14.727",
        "paymentModeDesc": "CRED CRD - BOND",
        "paymentModeCD": "RB",
        "active": 1,
        "isDeleted": "N",
        "posCode": 3
    },
    {
        "paymentModeMasterId": 172,
        "createUserId": 1,
        "updateUserId": 1,
        "createDateTime": "2022-06-23T10:43:40.473",
        "updateDateTime": "2022-06-23T10:43:40.473",
        "paymentModeDesc": "TRAVELERS CHECK",
        "paymentModeCD": "TC",
        "active": 1,
        "isDeleted": "N",
        "posCode": 4
    },
    {
        "paymentModeMasterId": 173,
        "createUserId": 1,
        "updateUserId": 1,
        "createDateTime": "2022-06-23T10:43:49.183",
        "updateDateTime": "2022-06-23T10:43:49.183",
        "paymentModeDesc": "WORK CREDIT",
        "paymentModeCD": "WC",
        "active": 1,
        "isDeleted": "N",
        "posCode": 9
    }
]

const newobj: any = {
    "paymentModeId": 1,
    "paymentModeMasterId": 161,
    "contractId": 2,
    "createUserId": 1,
    "updateUserId": 1,
    "createDatetime": "2022-06-16T16:56:23.34",
    "updateDatetime": "2022-06-16T16:56:23.34",
    "paymentModeDesc": "CASH - BOND",
    "paymentModeCD": "CB",
    "paymentModeNCR": 2,
    "paymentOpenDrawer": "Y",
    "active": 1,
    "isDeleted": "N"
}

const programManager: any[] = [
    {
        "id": 3,
        "accessFailedCount": 1,
        "concurrencyStamp": null,
        "email": "jack_mack@conduent.com",
        "emailConfirmed": true,
        "lockoutEnabled": true,
        "lockoutEnd": null,
        "normalizedEmail": null,
        "normalizedUserName": null,
        "passwordHash": null,
        "phoneNumber": null,
        "phoneNumberConfirmed": true,
        "securityStamp": null,
        "twoFactorEnabled": true,
        "userName": "JackM",
        "resetPassword": true,
        "firstName": "Jack",
        "lastLogin": "2022-04-26T18:28:24.3566667",
        "lastName": "Mack",
        "userEnabled": true,
        "secondaryEmail": null,
        "resetQuestions": true,
        "lastPasswordChangeDate": null,
        "passwordExpired": null,
        "domainId": 1,
        "officerBadgeNumber": null,
        "typedSignature": null,
        "officerRank": null,
        "internationalUsers": false,
        "createUserID": 1,
        "updateUserID": 1,
        "createDatetime": "2022-05-10T12:17:23.527",
        "updateDatetime": "2022-05-10T12:17:23.527",
        "isDeleted": "N"
    },
    {
        "id": 9,
        "accessFailedCount": 1,
        "concurrencyStamp": null,
        "email": "sam.smith@conduent.com",
        "emailConfirmed": true,
        "lockoutEnabled": true,
        "lockoutEnd": null,
        "normalizedEmail": null,
        "normalizedUserName": null,
        "passwordHash": null,
        "phoneNumber": null,
        "phoneNumberConfirmed": true,
        "securityStamp": null,
        "twoFactorEnabled": true,
        "userName": "SamS",
        "resetPassword": true,
        "firstName": "Sam",
        "lastLogin": "2022-04-23T18:28:24.38",
        "lastName": "Smith",
        "userEnabled": false,
        "secondaryEmail": null,
        "resetQuestions": true,
        "lastPasswordChangeDate": null,
        "passwordExpired": null,
        "domainId": 1,
        "officerBadgeNumber": null,
        "typedSignature": null,
        "officerRank": null,
        "internationalUsers": false,
        "createUserID": 1,
        "updateUserID": 1,
        "createDatetime": "2022-05-09T09:59:36.293",
        "updateDatetime": "2022-05-09T09:59:36.293",
        "isDeleted": "N"
    },
    {
        "id": 10,
        "accessFailedCount": 1,
        "concurrencyStamp": null,
        "email": "Jason.willam@conduent.com",
        "emailConfirmed": true,
        "lockoutEnabled": true,
        "lockoutEnd": null,
        "normalizedEmail": null,
        "normalizedUserName": null,
        "passwordHash": null,
        "phoneNumber": null,
        "phoneNumberConfirmed": true,
        "securityStamp": null,
        "twoFactorEnabled": true,
        "userName": "Jasonw",
        "resetPassword": true,
        "firstName": "Jason",
        "lastLogin": "2022-04-21T18:28:24.3866667",
        "lastName": "willam",
        "userEnabled": false,
        "secondaryEmail": null,
        "resetQuestions": true,
        "lastPasswordChangeDate": null,
        "passwordExpired": null,
        "domainId": 1,
        "officerBadgeNumber": null,
        "typedSignature": null,
        "officerRank": null,
        "internationalUsers": false,
        "createUserID": 1,
        "updateUserID": 1,
        "createDatetime": "2022-05-11T11:28:36.303",
        "updateDatetime": "2022-05-11T11:28:36.303",
        "isDeleted": "N"
    },
    {
        "id": 101,
        "accessFailedCount": 1,
        "concurrencyStamp": null,
        "email": "binit.ambastha@gmail.com",
        "emailConfirmed": true,
        "lockoutEnabled": true,
        "lockoutEnd": "2022-06-07T16:42:31.837+00:00",
        "normalizedEmail": null,
        "normalizedUserName": null,
        "passwordHash": null,
        "phoneNumber": null,
        "phoneNumberConfirmed": true,
        "securityStamp": null,
        "twoFactorEnabled": true,
        "userName": "BinitA",
        "resetPassword": true,
        "firstName": "Binit",
        "lastLogin": "2022-06-07T16:42:31.837",
        "lastName": "Ambastha",
        "userEnabled": true,
        "secondaryEmail": null,
        "resetQuestions": true,
        "lastPasswordChangeDate": "2022-06-07T16:42:31.837",
        "passwordExpired": true,
        "domainId": 1,
        "officerBadgeNumber": null,
        "typedSignature": null,
        "officerRank": null,
        "internationalUsers": false,
        "createUserID": 0,
        "updateUserID": 0,
        "createDatetime": "2022-06-07T16:42:49.397",
        "updateDatetime": "2022-06-07T16:42:49.397",
        "isDeleted": "N"
    },
    {
        "id": 102,
        "accessFailedCount": 1,
        "concurrencyStamp": null,
        "email": "binit.ambastha4@gmail.com",
        "emailConfirmed": true,
        "lockoutEnabled": true,
        "lockoutEnd": "2022-05-20T11:54:19.211+00:00",
        "normalizedEmail": null,
        "normalizedUserName": null,
        "passwordHash": null,
        "phoneNumber": null,
        "phoneNumberConfirmed": true,
        "securityStamp": null,
        "twoFactorEnabled": true,
        "userName": "BinitA",
        "resetPassword": true,
        "firstName": "Binit",
        "lastLogin": "2022-05-20T11:54:19.211",
        "lastName": "AmbasthaNew",
        "userEnabled": true,
        "secondaryEmail": null,
        "resetQuestions": true,
        "lastPasswordChangeDate": "2022-05-20T11:54:19.211",
        "passwordExpired": true,
        "domainId": 1,
        "officerBadgeNumber": null,
        "typedSignature": null,
        "officerRank": null,
        "internationalUsers": false,
        "createUserID": 0,
        "updateUserID": 0,
        "createDatetime": "2022-05-20T11:54:22.27",
        "updateDatetime": "2022-05-20T11:54:22.27",
        "isDeleted": "N"
    },
    {
        "id": 103,
        "accessFailedCount": 1,
        "concurrencyStamp": null,
        "email": "Nagaveera@conduent.com",
        "emailConfirmed": true,
        "lockoutEnabled": true,
        "lockoutEnd": "2022-05-20T12:13:56.16+00:00",
        "normalizedEmail": null,
        "normalizedUserName": null,
        "passwordHash": null,
        "phoneNumber": null,
        "phoneNumberConfirmed": true,
        "securityStamp": null,
        "twoFactorEnabled": true,
        "userName": "RaviKumarD",
        "resetPassword": true,
        "firstName": "RaviKumar",
        "lastLogin": "2022-05-20T12:13:56.16",
        "lastName": "Dendukuru",
        "userEnabled": true,
        "secondaryEmail": null,
        "resetQuestions": true,
        "lastPasswordChangeDate": "2022-05-20T12:13:56.16",
        "passwordExpired": true,
        "domainId": 1,
        "officerBadgeNumber": null,
        "typedSignature": null,
        "officerRank": null,
        "internationalUsers": false,
        "createUserID": 0,
        "updateUserID": 0,
        "createDatetime": "2022-05-20T12:14:00.517",
        "updateDatetime": "2022-05-20T12:14:00.517",
        "isDeleted": "N"
    },
    {
        "id": 104,
        "accessFailedCount": 1,
        "concurrencyStamp": null,
        "email": "vinay.vijayan@conduent.com",
        "emailConfirmed": true,
        "lockoutEnabled": true,
        "lockoutEnd": "2022-05-20T14:42:45.959+00:00",
        "normalizedEmail": null,
        "normalizedUserName": null,
        "passwordHash": null,
        "phoneNumber": null,
        "phoneNumberConfirmed": true,
        "securityStamp": null,
        "twoFactorEnabled": true,
        "userName": "VinayV",
        "resetPassword": true,
        "firstName": "Vinay",
        "lastLogin": "2022-05-20T14:42:45.959",
        "lastName": "Vijayan",
        "userEnabled": true,
        "secondaryEmail": null,
        "resetQuestions": true,
        "lastPasswordChangeDate": "2022-05-20T14:42:45.959",
        "passwordExpired": true,
        "domainId": 1,
        "officerBadgeNumber": null,
        "typedSignature": null,
        "officerRank": null,
        "internationalUsers": false,
        "createUserID": 0,
        "updateUserID": 0,
        "createDatetime": "2022-05-20T14:42:50.803",
        "updateDatetime": "2022-05-20T14:42:50.803",
        "isDeleted": "N"
    },
    {
        "id": 105,
        "accessFailedCount": 1,
        "concurrencyStamp": null,
        "email": "abc1@gmail.com",
        "emailConfirmed": true,
        "lockoutEnabled": true,
        "lockoutEnd": "2022-06-09T12:41:26.259+00:00",
        "normalizedEmail": null,
        "normalizedUserName": null,
        "passwordHash": null,
        "phoneNumber": null,
        "phoneNumberConfirmed": true,
        "securityStamp": null,
        "twoFactorEnabled": true,
        "userName": "test23t",
        "resetPassword": true,
        "firstName": "test23",
        "lastLogin": "2022-06-09T12:41:26.26",
        "lastName": "test45",
        "userEnabled": true,
        "secondaryEmail": null,
        "resetQuestions": true,
        "lastPasswordChangeDate": "2022-06-09T12:41:26.26",
        "passwordExpired": true,
        "domainId": 1,
        "officerBadgeNumber": null,
        "typedSignature": null,
        "officerRank": null,
        "internationalUsers": false,
        "createUserID": 0,
        "updateUserID": 0,
        "createDatetime": "2022-06-09T12:41:31.783",
        "updateDatetime": "2022-06-09T12:41:31.783",
        "isDeleted": "N"
    },
    {
        "id": 106,
        "accessFailedCount": 1,
        "concurrencyStamp": null,
        "email": "Apple@gmail.com",
        "emailConfirmed": true,
        "lockoutEnabled": true,
        "lockoutEnd": "2022-06-09T13:56:38.114+00:00",
        "normalizedEmail": null,
        "normalizedUserName": null,
        "passwordHash": null,
        "phoneNumber": null,
        "phoneNumberConfirmed": true,
        "securityStamp": null,
        "twoFactorEnabled": true,
        "userName": "AbhaA",
        "resetPassword": true,
        "firstName": "Abha",
        "lastLogin": "2022-06-09T13:56:38.114",
        "lastName": "Abhay",
        "userEnabled": true,
        "secondaryEmail": null,
        "resetQuestions": true,
        "lastPasswordChangeDate": "2022-06-09T13:56:38.114",
        "passwordExpired": true,
        "domainId": 1,
        "officerBadgeNumber": null,
        "typedSignature": null,
        "officerRank": null,
        "internationalUsers": true,
        "createUserID": 0,
        "updateUserID": 0,
        "createDatetime": "2022-06-09T13:56:42.503",
        "updateDatetime": "2022-06-09T13:56:42.503",
        "isDeleted": "N"
    },
    {
        "id": 107,
        "accessFailedCount": 1,
        "concurrencyStamp": null,
        "email": "simple@abc.com",
        "emailConfirmed": true,
        "lockoutEnabled": true,
        "lockoutEnd": "2022-06-09T14:05:23.2+00:00",
        "normalizedEmail": null,
        "normalizedUserName": null,
        "passwordHash": null,
        "phoneNumber": null,
        "phoneNumberConfirmed": true,
        "securityStamp": null,
        "twoFactorEnabled": true,
        "userName": "SimpleU",
        "resetPassword": true,
        "firstName": "Simple",
        "lastLogin": "2022-06-09T14:05:23.2",
        "lastName": "User",
        "userEnabled": true,
        "secondaryEmail": null,
        "resetQuestions": true,
        "lastPasswordChangeDate": "2022-06-09T14:05:23.2",
        "passwordExpired": true,
        "domainId": 1,
        "officerBadgeNumber": null,
        "typedSignature": null,
        "officerRank": null,
        "internationalUsers": true,
        "createUserID": 0,
        "updateUserID": 0,
        "createDatetime": "2022-06-09T14:05:24.077",
        "updateDatetime": "2022-06-09T14:05:24.077",
        "isDeleted": "N"
    },
    {
        "id": 108,
        "accessFailedCount": 1,
        "concurrencyStamp": null,
        "email": "Simple1@abc.com",
        "emailConfirmed": true,
        "lockoutEnabled": true,
        "lockoutEnd": "2022-06-09T14:07:24.932+00:00",
        "normalizedEmail": null,
        "normalizedUserName": null,
        "passwordHash": null,
        "phoneNumber": null,
        "phoneNumberConfirmed": true,
        "securityStamp": null,
        "twoFactorEnabled": true,
        "userName": "Simple1U",
        "resetPassword": true,
        "firstName": "Simple1",
        "lastLogin": "2022-06-09T14:07:24.932",
        "lastName": "User",
        "userEnabled": true,
        "secondaryEmail": null,
        "resetQuestions": true,
        "lastPasswordChangeDate": "2022-06-09T14:07:24.932",
        "passwordExpired": true,
        "domainId": 1,
        "officerBadgeNumber": null,
        "typedSignature": null,
        "officerRank": null,
        "internationalUsers": true,
        "createUserID": 0,
        "updateUserID": 0,
        "createDatetime": "2022-06-09T14:07:25.72",
        "updateDatetime": "2022-06-09T14:07:25.72",
        "isDeleted": "N"
    },
    {
        "id": 109,
        "accessFailedCount": 1,
        "concurrencyStamp": null,
        "email": "Simple2@user.com",
        "emailConfirmed": true,
        "lockoutEnabled": true,
        "lockoutEnd": "2022-06-09T14:08:19.837+00:00",
        "normalizedEmail": null,
        "normalizedUserName": null,
        "passwordHash": null,
        "phoneNumber": null,
        "phoneNumberConfirmed": true,
        "securityStamp": null,
        "twoFactorEnabled": true,
        "userName": "Simple2U",
        "resetPassword": true,
        "firstName": "Simple2",
        "lastLogin": "2022-06-09T14:08:19.837",
        "lastName": "User",
        "userEnabled": true,
        "secondaryEmail": null,
        "resetQuestions": true,
        "lastPasswordChangeDate": "2022-06-09T14:08:19.837",
        "passwordExpired": true,
        "domainId": 1,
        "officerBadgeNumber": null,
        "typedSignature": null,
        "officerRank": null,
        "internationalUsers": true,
        "createUserID": 0,
        "updateUserID": 0,
        "createDatetime": "2022-06-09T14:08:20.693",
        "updateDatetime": "2022-06-09T14:08:20.693",
        "isDeleted": "N"
    },
    {
        "id": 110,
        "accessFailedCount": 1,
        "concurrencyStamp": null,
        "email": "mahii@gmail.com",
        "emailConfirmed": true,
        "lockoutEnabled": true,
        "lockoutEnd": "2022-06-09T14:09:32.414+00:00",
        "normalizedEmail": null,
        "normalizedUserName": null,
        "passwordHash": null,
        "phoneNumber": null,
        "phoneNumberConfirmed": true,
        "securityStamp": null,
        "twoFactorEnabled": true,
        "userName": "sdfjk",
        "resetPassword": true,
        "firstName": "sdfj",
        "lastLogin": "2022-06-09T14:09:32.414",
        "lastName": "kjhsd",
        "userEnabled": true,
        "secondaryEmail": null,
        "resetQuestions": true,
        "lastPasswordChangeDate": "2022-06-09T14:09:32.414",
        "passwordExpired": true,
        "domainId": 1,
        "officerBadgeNumber": null,
        "typedSignature": null,
        "officerRank": null,
        "internationalUsers": false,
        "createUserID": 0,
        "updateUserID": 0,
        "createDatetime": "2022-06-09T14:09:36.567",
        "updateDatetime": "2022-06-09T14:09:36.567",
        "isDeleted": "N"
    },
    {
        "id": 111,
        "accessFailedCount": 1,
        "concurrencyStamp": null,
        "email": "virushka@gmail.com",
        "emailConfirmed": true,
        "lockoutEnabled": true,
        "lockoutEnd": "2022-06-09T14:21:05.318+00:00",
        "normalizedEmail": null,
        "normalizedUserName": null,
        "passwordHash": null,
        "phoneNumber": null,
        "phoneNumberConfirmed": true,
        "securityStamp": null,
        "twoFactorEnabled": true,
        "userName": "AaravA",
        "resetPassword": true,
        "firstName": "Aarav",
        "lastLogin": "2022-06-09T14:21:05.318",
        "lastName": "Aryan",
        "userEnabled": true,
        "secondaryEmail": null,
        "resetQuestions": true,
        "lastPasswordChangeDate": "2022-06-09T14:21:05.318",
        "passwordExpired": true,
        "domainId": 1,
        "officerBadgeNumber": null,
        "typedSignature": null,
        "officerRank": null,
        "internationalUsers": false,
        "createUserID": 0,
        "updateUserID": 0,
        "createDatetime": "2022-06-09T14:21:06.173",
        "updateDatetime": "2022-06-09T14:21:06.173",
        "isDeleted": "N"
    },
    {
        "id": 112,
        "accessFailedCount": 1,
        "concurrencyStamp": null,
        "email": "virushka1@gmail.com",
        "emailConfirmed": true,
        "lockoutEnabled": true,
        "lockoutEnd": "2022-06-09T15:36:14.541+00:00",
        "normalizedEmail": null,
        "normalizedUserName": null,
        "passwordHash": null,
        "phoneNumber": null,
        "phoneNumberConfirmed": true,
        "securityStamp": null,
        "twoFactorEnabled": true,
        "userName": "Aarav1A",
        "resetPassword": true,
        "firstName": "Aarav1",
        "lastLogin": "2022-06-09T15:36:14.541",
        "lastName": "Aryan",
        "userEnabled": true,
        "secondaryEmail": null,
        "resetQuestions": true,
        "lastPasswordChangeDate": "2022-06-09T15:36:14.541",
        "passwordExpired": true,
        "domainId": 1,
        "officerBadgeNumber": null,
        "typedSignature": null,
        "officerRank": null,
        "internationalUsers": false,
        "createUserID": 0,
        "updateUserID": 0,
        "createDatetime": "2022-06-09T15:36:15.23",
        "updateDatetime": "2022-06-09T15:36:15.23",
        "isDeleted": "N"
    },
    {
        "id": 113,
        "accessFailedCount": 1,
        "concurrencyStamp": null,
        "email": "shaheen@gmail.com",
        "emailConfirmed": true,
        "lockoutEnabled": true,
        "lockoutEnd": "2022-06-09T18:21:03.15+00:00",
        "normalizedEmail": null,
        "normalizedUserName": null,
        "passwordHash": null,
        "phoneNumber": null,
        "phoneNumberConfirmed": true,
        "securityStamp": null,
        "twoFactorEnabled": true,
        "userName": "GibbsA",
        "resetPassword": true,
        "firstName": "Gibbs",
        "lastLogin": "2022-06-09T18:21:03.15",
        "lastName": "Abhay",
        "userEnabled": true,
        "secondaryEmail": null,
        "resetQuestions": true,
        "lastPasswordChangeDate": "2022-06-09T18:21:03.15",
        "passwordExpired": true,
        "domainId": 1,
        "officerBadgeNumber": null,
        "typedSignature": null,
        "officerRank": null,
        "internationalUsers": true,
        "createUserID": 0,
        "updateUserID": 0,
        "createDatetime": "2022-06-09T18:21:04.813",
        "updateDatetime": "2022-06-09T18:21:04.813",
        "isDeleted": "N"
    },
    {
        "id": 114,
        "accessFailedCount": 1,
        "concurrencyStamp": null,
        "email": "Babar@gmail.com",
        "emailConfirmed": true,
        "lockoutEnabled": true,
        "lockoutEnd": "2022-06-09T18:22:20.664+00:00",
        "normalizedEmail": null,
        "normalizedUserName": null,
        "passwordHash": null,
        "phoneNumber": null,
        "phoneNumberConfirmed": true,
        "securityStamp": null,
        "twoFactorEnabled": true,
        "userName": "HrashalA",
        "resetPassword": true,
        "firstName": "Hrashal",
        "lastLogin": "2022-06-09T18:22:20.664",
        "lastName": "Aryan",
        "userEnabled": true,
        "secondaryEmail": null,
        "resetQuestions": true,
        "lastPasswordChangeDate": "2022-06-09T18:22:20.664",
        "passwordExpired": true,
        "domainId": 1,
        "officerBadgeNumber": null,
        "typedSignature": null,
        "officerRank": null,
        "internationalUsers": true,
        "createUserID": 0,
        "updateUserID": 0,
        "createDatetime": "2022-06-09T18:22:21.857",
        "updateDatetime": "2022-06-09T18:22:21.857",
        "isDeleted": "N"
    },
    {
        "id": 115,
        "accessFailedCount": 1,
        "concurrencyStamp": null,
        "email": "fakhar@gmail.com",
        "emailConfirmed": true,
        "lockoutEnabled": true,
        "lockoutEnd": "2022-06-09T18:24:49.966+00:00",
        "normalizedEmail": null,
        "normalizedUserName": null,
        "passwordHash": null,
        "phoneNumber": null,
        "phoneNumberConfirmed": true,
        "securityStamp": null,
        "twoFactorEnabled": true,
        "userName": "AmirS",
        "resetPassword": true,
        "firstName": "Amir",
        "lastLogin": "2022-06-09T18:24:49.966",
        "lastName": "Sharda",
        "userEnabled": true,
        "secondaryEmail": null,
        "resetQuestions": true,
        "lastPasswordChangeDate": "2022-06-09T18:24:49.966",
        "passwordExpired": true,
        "domainId": 1,
        "officerBadgeNumber": null,
        "typedSignature": null,
        "officerRank": null,
        "internationalUsers": true,
        "createUserID": 0,
        "updateUserID": 0,
        "createDatetime": "2022-06-09T18:29:52.983",
        "updateDatetime": "2022-06-09T18:29:52.983",
        "isDeleted": "N"
    },
    {
        "id": 116,
        "accessFailedCount": 1,
        "concurrencyStamp": null,
        "email": "hasan@gmail.com",
        "emailConfirmed": true,
        "lockoutEnabled": true,
        "lockoutEnd": "2022-06-09T18:26:12.363+00:00",
        "normalizedEmail": null,
        "normalizedUserName": null,
        "passwordHash": null,
        "phoneNumber": null,
        "phoneNumberConfirmed": true,
        "securityStamp": null,
        "twoFactorEnabled": true,
        "userName": "RudrK",
        "resetPassword": true,
        "firstName": "Rudr",
        "lastLogin": "2022-06-09T18:26:12.363",
        "lastName": "Kesh",
        "userEnabled": true,
        "secondaryEmail": null,
        "resetQuestions": true,
        "lastPasswordChangeDate": "2022-06-09T18:26:12.363",
        "passwordExpired": true,
        "domainId": 1,
        "officerBadgeNumber": null,
        "typedSignature": null,
        "officerRank": null,
        "internationalUsers": true,
        "createUserID": 0,
        "updateUserID": 0,
        "createDatetime": "2022-06-09T18:26:13.417",
        "updateDatetime": "2022-06-09T18:26:13.417",
        "isDeleted": "N"
    },
    {
        "id": 117,
        "accessFailedCount": 1,
        "concurrencyStamp": null,
        "email": "shadab@gmail.com",
        "emailConfirmed": true,
        "lockoutEnabled": true,
        "lockoutEnd": "2022-06-09T18:28:17.961+00:00",
        "normalizedEmail": null,
        "normalizedUserName": null,
        "passwordHash": null,
        "phoneNumber": null,
        "phoneNumberConfirmed": true,
        "securityStamp": null,
        "twoFactorEnabled": true,
        "userName": "MalikS",
        "resetPassword": true,
        "firstName": "Malik",
        "lastLogin": "2022-06-09T18:28:17.961",
        "lastName": "Sania",
        "userEnabled": true,
        "secondaryEmail": null,
        "resetQuestions": true,
        "lastPasswordChangeDate": "2022-06-09T18:28:17.961",
        "passwordExpired": true,
        "domainId": 1,
        "officerBadgeNumber": null,
        "typedSignature": null,
        "officerRank": null,
        "internationalUsers": true,
        "createUserID": 0,
        "updateUserID": 0,
        "createDatetime": "2022-06-09T18:28:19",
        "updateDatetime": "2022-06-09T18:28:19",
        "isDeleted": "N"
    },
    {
        "id": 118,
        "accessFailedCount": 1,
        "concurrencyStamp": null,
        "email": "imamulhaq@gmail.com",
        "emailConfirmed": true,
        "lockoutEnabled": true,
        "lockoutEnd": "2022-06-09T18:34:02.429+00:00",
        "normalizedEmail": null,
        "normalizedUserName": null,
        "passwordHash": null,
        "phoneNumber": null,
        "phoneNumberConfirmed": true,
        "securityStamp": null,
        "twoFactorEnabled": true,
        "userName": "ViraatA",
        "resetPassword": true,
        "firstName": "Viraat",
        "lastLogin": "2022-06-09T18:34:02.429",
        "lastName": "Abhi",
        "userEnabled": true,
        "secondaryEmail": null,
        "resetQuestions": true,
        "lastPasswordChangeDate": "2022-06-09T18:34:02.429",
        "passwordExpired": true,
        "domainId": 1,
        "officerBadgeNumber": null,
        "typedSignature": null,
        "officerRank": null,
        "internationalUsers": true,
        "createUserID": 0,
        "updateUserID": 0,
        "createDatetime": "2022-06-13T13:21:21.187",
        "updateDatetime": "2022-06-13T13:21:21.187",
        "isDeleted": "N"
    },
    {
        "id": 119,
        "accessFailedCount": 1,
        "concurrencyStamp": null,
        "email": "binitkambastha@gmail.com",
        "emailConfirmed": true,
        "lockoutEnabled": true,
        "lockoutEnd": "2022-06-16T12:27:42.555+00:00",
        "normalizedEmail": null,
        "normalizedUserName": null,
        "passwordHash": null,
        "phoneNumber": null,
        "phoneNumberConfirmed": true,
        "securityStamp": null,
        "twoFactorEnabled": true,
        "userName": "binita",
        "resetPassword": true,
        "firstName": "binit",
        "lastLogin": "2022-06-16T12:27:42.555",
        "lastName": "ambastha",
        "userEnabled": true,
        "secondaryEmail": null,
        "resetQuestions": true,
        "lastPasswordChangeDate": "2022-06-16T12:27:42.555",
        "passwordExpired": true,
        "domainId": 1,
        "officerBadgeNumber": null,
        "typedSignature": null,
        "officerRank": null,
        "internationalUsers": false,
        "createUserID": 0,
        "updateUserID": 0,
        "createDatetime": "2022-06-16T12:28:14.553",
        "updateDatetime": "2022-06-16T12:28:14.553",
        "isDeleted": "N"
    },
    {
        "id": 120,
        "accessFailedCount": 1,
        "concurrencyStamp": null,
        "email": "test45@gmail.com",
        "emailConfirmed": true,
        "lockoutEnabled": true,
        "lockoutEnd": "2022-06-16T12:41:36.896+00:00",
        "normalizedEmail": null,
        "normalizedUserName": null,
        "passwordHash": null,
        "phoneNumber": null,
        "phoneNumberConfirmed": true,
        "securityStamp": null,
        "twoFactorEnabled": true,
        "userName": "testt",
        "resetPassword": true,
        "firstName": "test",
        "lastLogin": "2022-06-16T12:41:36.896",
        "lastName": "test",
        "userEnabled": true,
        "secondaryEmail": null,
        "resetQuestions": true,
        "lastPasswordChangeDate": "2022-06-16T12:41:36.896",
        "passwordExpired": true,
        "domainId": 1,
        "officerBadgeNumber": null,
        "typedSignature": null,
        "officerRank": null,
        "internationalUsers": false,
        "createUserID": 0,
        "updateUserID": 0,
        "createDatetime": "2022-06-16T12:42:09.26",
        "updateDatetime": "2022-06-16T12:42:09.26",
        "isDeleted": "N"
    }
]

const newContractSetting: any = {
    "contractSettingsID": 2,
    "contractID": 2,
    "citationNumberFormat": "7",
    "citationSequenceNumber": 7,
    "eventSequenceNumber": 1,
    "batchSequenceNumber": 7,
    "maximumBatchSize": 7,
    "storageLocation": "y",
    "active": true,
    "pointOfContactEmail": "xyz@gmail.com",
    "pointOfContactName": "xyz",
    "neighborThreshold": 7,
    "clearPlate": false,
    "batchEncryptionPassword": "7",
    "overtimeCutoffTime": "10:30:00",
    "showDLBasic": false,
    "showDobGender": false,
    "showDriverDescriptors": false,
    "plateExamplesFileName": "y",
    "enablePlateExample": false,
    "showCoOwner": false,
    "warningCitationNumberFormat": "7",
    "warningCitationSequenceNumber": 0,
    "tolCitationNumberFormat": "7",
    "tolCitationSequenceNumber": 7,
    "convenienceFee": 7.00,
    "convenienceFeePerCitation": true,
    "convenienceFeePerPlate": true,
    "enableOmniChannel": false,
    "percentageBasedConvenienceFee": true,
    "percentageConvenienceFee": 7.00,
    "thresholdAmountConvenienceFee": 7.00,
    "offlineBatchLimit": 7,
    "prevYearCitationSequenceNumber": 0,
    "enableOfflinePrintingContract": false,
    "defaultCitationSequenceNumber": 0,
    "enableCustomerServiceTracking": false,
    "secondCitationNumberFormat": "7",
    "secondCitationSequenceNumber": 7,
    "enableDistribution": false,
    "appTimeout": 160,
    "maxoutAdvanceSearchResults": 7,
    "courtEventsCutOffDays": 7,
    "maxoutPrintingArchiveResults": 7,
    "partialPayment": true,
    "enableDistributionDisplay": false,
    "bootFee": 0,
    "towFee": 0,
    "firstSDayFee": 0,
    "multSDayFee": 0,
    "bootEscapeType": 0,
    "renewalRppFee": 0,
    "bootTickCnt": 0,
    "holdTickCnt": 0,
    "databaseName": 0,
    "bootTowAmt": 0,
    "skeletonPayInd": "y",
    "scheduleInd": "y",
    "skeletonDispInd": "y",
    "skeletonSuspInd": "y",
    "rejectFiller": "y",
    "bootDelayDays": 0,
    "ticksPerRec": 0,
    "stdDevInd": "y",
    "payGracePD": 0,
    "suspHearingDays": 0,
    "loadSW": 0,
    "createUserID": 1,
    "updateUserID": 1,
    "createDatetime": "2022-04-28T14:25:50.633",
    "updateDatetime": "2022-04-28T14:25:50.633",
    "isDeleted": "N"
}

const newClientMasterList: any = [
    {
        "clientsId": 2,
        "clientsName": "Suffolk",
        "timeZonesID": 1,
        "TimeZoneName": "Atlantic Time Zone",
        "clientsNumber": "SU",
        "clientsShortName": "YC",
        "stateProvincesID": 1,
        "stateProvincesName": "New Brunswick",
        "active": "Y",
        "createUserID": 1,
        "updateUserID": 1,
        "createDatetime": "2022-04-28T12:05:03.04",
        "updateDatetime": "2022-04-28T12:05:03.04",
        "isDeleted": "N"
    },
    {
        "clientsId": 3,
        "clientsName": "Sanfran",
        "timeZonesID": 1,
        "TimeZoneName": "Atlantic Time Zone",
        "clientsNumber": "SF",
        "clientsShortName": "HC",
        "stateProvincesID": 1,
        "stateProvincesName": "New Brunswick",
        "active": "N",
        "createUserID": 1,
        "updateUserID": 1,
        "createDatetime": "2022-06-23T07:54:50.697",
        "updateDatetime": "2022-06-23T07:54:50.697",
        "isDeleted": "N"
    },
    {
        "clientsId": 13,
        "clientsName": "Washington DC",
        "timeZonesID": 2,
        "TimeZoneName": "Eastern Time Zone",
        "clientsNumber": "09",
        "clientsShortName": "WDCE",
        "stateProvincesID": 34,
        "stateProvincesName": "District of Columbia",
        "active": "N",
        "createUserID": 0,
        "updateUserID": 0,
        "createDatetime": "2022-05-04T06:46:58.937",
        "updateDatetime": "2022-05-04T06:46:58.937",
        "isDeleted": "N"
    },
    {
        "clientsId": 92,
        "clientsName": "Washington",
        "timeZonesID": 2,
        "TimeZoneName": "Eastern Time Zone",
        "clientsNumber": "1503",
        "clientsShortName": "DC",
        "stateProvincesID": 2,
        "stateProvincesName": "Missouri",
        "active": "N",
        "createUserID": 0,
        "updateUserID": 0,
        "createDatetime": "2022-06-14T05:09:27.757",
        "updateDatetime": "2022-06-14T05:09:27.757",
        "isDeleted": "N"
    },
    {
        "clientsId": 93,
        "clientsName": "mno",
        "timeZonesID": 1,
        "TimeZoneName": "Atlantic Time Zone",
        "clientsNumber": "8863",
        "clientsShortName": "pqr123",
        "stateProvincesID": 1,
        "stateProvincesName": "New Brunswick",
        "active": "N",
        "createUserID": 0,
        "updateUserID": 0,
        "createDatetime": "2022-06-23T08:40:21.92",
        "updateDatetime": "2022-06-23T08:40:21.92",
        "isDeleted": "N"
    },
    {
        "clientsId": 94,
        "clientsName": "icon",
        "timeZonesID": 4,
        "TimeZoneName": "Mountain Time Zone",
        "clientsNumber": "5522",
        "clientsShortName": "testenable",
        "stateProvincesID": 4,
        "stateProvincesName": "Wisconsin",
        "active": "Y",
        "createUserID": 0,
        "updateUserID": 0,
        "createDatetime": "2022-06-23T08:41:24.783",
        "updateDatetime": "2022-06-23T08:41:24.783",
        "isDeleted": "N"
    },
    {
        "clientsId": 95,
        "clientsName": "test",
        "timeZonesID": 4,
        "TimeZoneName": "Mountain Time Zone",
        "clientsNumber": "7777",
        "clientsShortName": "recheck",
        "stateProvincesID": 4,
        "stateProvincesName": "Wisconsin",
        "active": "N",
        "createUserID": 0,
        "updateUserID": 0,
        "createDatetime": "2022-06-23T08:42:02.637",
        "updateDatetime": "2022-06-23T08:42:02.637",
        "isDeleted": "N"
    }
]

const timeZoneMaster: any = [
    {
        "contractTypesId": 1,
        "contractTypesName": "Red Light"
    },
    {
        "contractTypesId": 2,
        "contractTypesName": "Speed"
    },
    {
        "contractTypesId": 3,
        "contractTypesName": "Parking"
    }
]


export class ContractServiceStub {

    getContract(): Observable<any[]> {
        return of(contractList)
    }
    getContarctSettingList(): Observable<any[]> {
        return of(contractList)
    }
    getClientMaster(): Observable<any[]> {
        return of(newClientMasterList)
    }
    getContractMaster(): Observable<any[]> {
        return of(newContractSetting)
    }
    getTimeZoneMaster(): Observable<any[]> {
        return of(timeZoneMaster)
    }
    getStateProvincesMaster(): Observable<any[]> {
        return of(newContractSetting)
    }
    getProgramManager(): Observable<any[]> {
        return of(programManager)
    }
    updateContract(updateReq: any): Observable<any> {
        return of({ status: 'Success', details: [{ code: '200' }] });
    }
    getPaymentMethod(): Observable<any> {
        return of(clientPaymentMode);
    }
    addTickettypeList(): Observable<any> {
        return of(newobj);
    }
    UpdateTicketType(): Observable<any> {
        return of(newobj);
    }
    editContract(): Observable<any> {
        return of({
            "name": "Suffolk",
            "identifierName": "default",
            "codeName": null,
            "payByWebCode": 0,
            "programManagerId": 3,
            "stateProvinceName": "Hawaii",
            "timeZone": null,
            "cbiDashboardLink": null,
            "passwordExpirationLength": 90,
            "mavroCode": null,
            "twoFactorEnabled": true,
            "partialPaymentValidation": true,
            "contractTypeName": null,
            "contractName": "Default",
            "programManagerName": "Jack Mack",
            "clientsID": 2,
            "contractsID": 1,
            "stateProvincesID": 1,
            "timeZonesID": 1,
            "contractTypeId": 2,
            "partialPaymentDueValidation": true,
            "active": true,
            "createUserID": 0,
            "updateUserID": 0,
            "createDatetime": "0001-01-01T00:00:00",
            "updateDatetime": "0001-01-01T00:00:00",
            "isDeleted": "N"
        });
    }

    createContract(): Observable<any> {
        return of({ status: 'Success', details: [{ code: '200' }] });
    }

    deleteTicketType(): Observable<any> {
        return of(newobj);
    }
    addContractSetting(data: any): Observable<any> {
        return of({ status: data.contractSettingsModel.contractID == 1 ? 'Success' : 'ERROR', details: [{ code: '200', fieldName: 'contractID' }] });
    }

    UpdateContarctSettingList(data: any): Observable<any> {
        return of({ status: data.contractSettingsModel.contractID == 1 ? 'Success' : 'ERROR', details: [{ code: '200', fieldName: 'contractID' }] });
    }

    getTimeZoneProvincesDetailsByClientId(data: any): Observable<any> {
        return of(
            {
                status: data == 1 ? 'Success' : 'Error',
                timeZonesID: 1,
                stateProvincesID: 1,
                details: [{ code: '200', message: 'Fail' }]
            }
        );
    }

    toggleContract(url: string, data: any, CW5type?: boolean): Observable<any> {
		return of({status: 'Success', details: [{code: '200'}]});
	}
}