export interface NoticeDetails
{
    noticeID: number | null,
    batchID: number | null,
    contractID: number | null,
    accountEntityID: number | null,
    mailDate: string | null,
    noticeStatusID: number | null,
    printDate: string | null,
    templatesID: number | null,
    violationDateTime: string | null,
    location: string | null,
    noticeTypeID: number | null,
    noticeTypeName: string | null,
    active: string | null,
    dueDate: string | null,
    formNumber: number | null,
    sequenceNumber: number | null,
    pageNumber: number | null,
    ticketTypeID: number | null,
    statePlate: string | null,
    registryEffectiveDate: string | null,
    licenseClass: string | null,
    licenseNumber: string | null,
    multiOwnerID: number | null,
    fullName: string | null,
    streetLine1: string | null,
    streetLine2: string | null,
    streetLine3: string | null,
    countriesID: number | null,
    city: string | null,
    stateProvincesID: number | null,
    zipCode: string | null,
    sex: string | null,
    dateOfBirth: string | null,
    manuaL_RJCT_SW: number | null,
    nixieDate: string | null,
    scheduleHearingDate: string | null,
    lastPageiND: number | null,
    numberOfPages: number | null,
    ticketCount: number | null,
    totalDue: number | null,
    maxFinePens: number | null,
    mailStatus: string | null,
    fillAL1: string | null,
    companyName: string | null,
    amountDue: number | null,
    amountPending:  number | null,
    paymentDate: string | null,
    amountPaid: number | null,
    account: number | null,
    facimile: number | null,
    address: string | null,
    noticeTicketList: noticeTicketList | null[],
    createUserID: number | null,
    updateUserID: number | null,
    createDatetime: string | null,
    updateDatetime: string | null,
    isDeleted: string | null
}

export interface noticeTicketList {
    citationNumber: string,
    issueDatetime: string,
    make: string,
    locationDesc: string,
    amountDue: number,
    amountPaid: number,
    violName: string
}